export const stage:any =  {
    'INIT':'المخزن',
    'AGENTOP':"عند المندوب",
    'CNCL':'الراجع',
    'DLV':'الواصل',
    'BRANCHES':'النقل بين الفروع',
    'NEWCUSTLOGI':'شحنات جديدة عند العميل',
}
export const step:any =  {
    'NEW_ONWAY': 'شحنات جديده قادمة في الطريق',
    'NEWINSTORE': 'داخل المخزن',
    'PRINTMANIFEST': 'طباعة المنفيست لمندوبين التوصيل',
    'ONWAY': 'قيد التوصيل',
    'RTN_WITHAGENT': 'راجع عند المندوب',
    'POSTPONED': 'مؤجل',
    'TRY_AGAIN': 'إعادة توصيل',
    'RTN_INSTORE': 'شحنات راجعه في المخزن',
    'FORCE_DLV': 'واصل أجباري',
    'DLEIVERD': 'شحنات سلمت بنجاح',
    'PART_SUCC': 'تسليم جزئيا أو أستبدال',
    'SUCC_CHANGEPRICE': 'سلمت مع تغيير المبلغ',
    'MANIFEST_BRANCHES': 'طباعة منفيست للفروع',
    'LIAISONAGT_NEWONWAY': 'شحنات جديدة بين فرعين',
    'RTN_WITHLIAISONAGENT': 'استلام الراجع من الفروع',
    'RTN_INSTORE_WAITLIAISON': 'رواجع الفروع في المخزن',
    'RTN_MANIFEST_LIAISON': 'رواجع جاهزة للتسليم للفروع',
    'READYTOPRINT': 'جاهز للطبع',
    'READYTOPICKUP': 'جاهز للبيك اب'
}
export const stepId:any =  {
    'NEW_ONWAY':17,
    'NEWINSTORE': 9,
    'PRINTMANIFEST':12,
    'ONWAY': 22,
    'RTN_WITHAGENT':23,
    'POSTPONED': 24,
    'TRY_AGAIN': 36,
    'RTN_INSTORE': 4,
    'FORCE_DLV': 35,
    'DLEIVERD': 11,
    'PART_SUCC': 29,
    'SUCC_CHANGEPRICE': 30,
    'MANIFEST_BRANCHES': 28,
    'LIAISONAGT_NEWONWAY': 21,
    'RTN_WITHLIAISONAGENT': 26,
    'RTN_INSTORE_WAITLIAISON': 27,
    'RTN_MANIFEST_LIAISON': 34,
    'READYTOPRINT': 31,
    'READYTOPICKUP': 32
}
